@startuml
!theme cerulean-outline

start

if (Is Local Mode?) then (no)
    :Check/Initialize
    Kubernetes Secret;
endif

if (CA Certificate and Key exists?) then (yes)
    :Load Certificate
    and Key;
else (no)
    :Create Certificate
    and Key;
    :Store Certificate
    and Key;
    :Load Certificate
    and Key;
endif

stop

@enduml
