@startuml
!theme cerulean-outline

participant "Source" as s
participant "Translator" as t
participant "Application" as a

s -> t: Incoming request
activate t
    t -> t: Check if "x-wirepact-identity"\nheader is set
    note left
        No HTTP header is set.
        Therefore, the request is forwarded
    end note
    t -> a: Forward request
deactivate t

@enduml
