@startuml
!theme cerulean-outline

participant "Source" as s
participant "Translator" as t
participant "Application" as a

s -> t: Incoming request
activate t
    t -> t: Check if "x-wirepact-identity"\nheader is set
    t -> t: Search for username/password combination
    t -> t: Remove "x-wirepact-identity" header
    t -> t: Add "Authorization" header with Basic credentials
    t -> a: Forward request
deactivate t

@enduml
